FROM python:3.13

RUN apt-get update && apt-get install -y ffmpeg

RUN pip install --upgrade pip
RUN pip install poetry

ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock
RUN poetry sync --only main

EXPOSE 8080
COPY . .

ENTRYPOINT ["poetry", "run"]
CMD ["python", "-m", "uvicorn", "main:app", "--host=0.0.0.0", "--port=8080"]
