FROM python:3.9

RUN apt-get update && apt-get install -y ffmpeg

RUN pip install --upgrade pip
RUN pip install poetry

ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY poetry.lock pyproject.toml ./
RUN poetry install --without dev --no-root

COPY . .

EXPOSE 8080

ENTRYPOINT [ "poetry", "run"]
CMD ["python3", "-m", "uvicorn", "main:app", "--host=0.0.0.0", "--port=8080"]
